spring:
  integration:
    jdbc:
      initialize-schema: always
  jpa:
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: orders
    password: password
server:
  port: 0

